# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-05 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_notifications', '0002_noticetype_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticesetting',
            name='scoping_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType'),
        ),
    ]
